// src/components/shared/avatar/avatar.svelte
<script>
	import { onMount } from 'svelte';
	import { cn } from '~/libs/utils';

	let { class: className, src, fallback, ...props } = $props();

	let loading = $state(true);
	let loaded = $state(false);
	let failed = $state(false);
	onMount(() => {
		const img = new Image();
		img.src = src;

		img.onload = () => {
			loading = false;
			loaded = true;
		};

		img.onerror = () => {
			loading = false;
			failed = true;
		};
	});
</script>

{#if loaded}
	<img {src} class={cn('aspect-square size-full rounded-full', className)} {...props} />
{:else if failed || loading}
	<div
		class={cn(
			'flex aspect-square size-full items-center justify-center rounded-full',
			className,
			'bg-muted dark:bg-muted'
		)}
		{...props}
	>
		{fallback}
	</div>
{/if}

// src/components/shared/avatar.tsx
import * as React from 'react';
import * as AvatarPrimitive from '@radix-ui/react-avatar';

import { cn } from '~/libs/utils';

function Avatar({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Root>) {
	return (
		<AvatarPrimitive.Root
			data-slot="avatar"
			className={cn('relative flex size-8 shrink-0 overflow-hidden rounded-full', className)}
			{...props}
		/>
	);
}

function AvatarImage({ className, ...props }: React.ComponentProps<typeof AvatarPrimitive.Image>) {
	return (
		<AvatarPrimitive.Image
			data-slot="avatar-image"
			className={cn('aspect-square size-full', className)}
			{...props}
		/>
	);
}

function AvatarFallback({
	className,
	...props
}: React.ComponentProps<typeof AvatarPrimitive.Fallback>) {
	return (
		<AvatarPrimitive.Fallback
			data-slot="avatar-fallback"
			className={cn('bg-muted flex size-full items-center justify-center rounded-full', className)}
			{...props}
		/>
	);
}

const AvatarComponent: React.FC<AvatarComponentProps> = ({ src, alt, fallback, className }) => {
	return (
		<Avatar className={className}>
			<AvatarImage src={src} alt={alt} />
			<AvatarFallback>{fallback}</AvatarFallback>
		</Avatar>
	);
};

export default AvatarComponent;

interface AvatarComponentProps {
	src?: string;
	alt?: string;
	fallback: string;
	className?: string;
}

export { Avatar, AvatarImage, AvatarFallback };
