// src/components/home/about.svelte
<script lang="ts">
	import profile from '~/constants/profile';
</script>

<section id="about">
	<div class="flex flex-col gap-y-2">
		<div>
			<h2 class="text-xl font-bold">About</h2>
		</div>
		<div>
			<p
				class="prose max-w-full text-pretty font-sans text-sm text-muted-foreground dark:prose-invert"
			>
				{profile.description}
			</p>
		</div>
	</div>
</section>

// src/components/home/about.tsx
import profile from '~/constants/profile';

export default function AboutSection() {
	return (
		<section id="about">
			<div className="flex flex-col gap-y-2">
				<div>
					<h2 className="text-xl font-bold">About</h2>
				</div>
				<div>
					<p className="prose text-muted-foreground dark:prose-invert max-w-full font-sans text-sm text-pretty">
						{profile.description}
					</p>
				</div>
			</div>
		</section>
	);
}
